apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prod
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres-root-password
  POSTGRES_DB: plasticycle